name: erickhar
runtime:
  name: nodejs
  options:
    packagemanager: bun
description: erickhar.com infrastructure — Cloudflare DNS + Zero Trust
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
