run: single multiple movable

single:
	GOOS=js GOARCH=wasm go build -o ../../../static/wasm/single-raycast.wasm single_raycast.go

multiple:
	GOOS=js GOARCH=wasm go build -o ../../../static/wasm/multiple-raycasts.wasm multiple_raycasts.go

dda:
	GOOS=js GOARCH=wasm go build -o ../../../static/wasm/movable-character.wasm movable_character.go
